fix reload and try to make vim xdg compliant

diff --git a/xdg-config-home/zsh/functions/reload b/xdg-config-home/zsh/functions/reload
--- a/xdg-config-home/zsh/functions/reload
+++ b/xdg-config-home/zsh/functions/reload
@@ -5,7 +5,7 @@ function reload() {
     local basename="$1"
 
     local config_dir file_path
-    for config_dir in "$xdg_config_dirs[@]"; do
+    for config_dir in "$XDG_CONFIG_HOME" "$xdg_config_dirs[@]"; do
         if [[ -e "$config_dir/zsh/zshenv.d/$basename" ]]; then
             file_path="$config_dir/zsh/zshenv.d/$basename"
             break
@@ -17,7 +17,7 @@ function reload() {
     done
 
     if [[ -z "$file_path" ]]; then
-        echo 'File not found under $XDG_CONFIG_DIRS' >&2
+        echo 'File not found under $XDG_CONFIG_HOME or $xdg_config_dirs' >&2
         return 1
     fi
 
